// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexoWebApplication.Infrastructure.Data;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace NexoWebApplication.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251122070913_NomeDaNovaMigration")]
    partial class NomeDaNovaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexoWebApplication.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TN_CLIENTE", (string)null);
                });

            modelBuilder.Entity("NexoWebApplication.Domain.Entities.DescricaoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdocaoTecnologia")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("AnosExperiencia")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("AreaEstudo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("InteresseMudar")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("OcupacaoAtual")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Satisfacao")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("TN_DESCRICAO_CLIENTE", (string)null);
                });

            modelBuilder.Entity("NexoWebApplication.Domain.Entities.DescricaoCliente", b =>
                {
                    b.HasOne("NexoWebApplication.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Descricoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("NexoWebApplication.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Descricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
